---
name: POE-Component-WWW-Rafb-Create
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: non-blocking wrapper around WWW::Rafb::Create
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.2222
  POE::Filter::Reference: 1.222
  POE::Wheel::Run: 1.2222
  WWW::Rafb::Create: 0.001
build_requires:
  Test::More: 0
provides:
  POE::Component::WWW::Rafb::Create:
    file: lib/POE/Component/WWW/Rafb/Create.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
